author:
  name: Shadab Zafar
  url: https://github.com/dufferzafar

title: zafar's log
tagline: life. philosophy. code
description: life. philosophy. code

theme: minima

permalink: /:year/:title/

# highlighter: pygments

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - Blog.sublime-project
  - Blog.sublime-workspace

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

timezone: Asia/Kolkata

future: true
